export const content = {
  en: {
    navAbout: "About",
    navFeatures: "Features",
    navPricing: "Pricing",
    navFAQ: "FAQ",
    navContact: "Contact",
    navPartners: "Partners",
    navBlog: "Blog",
    heroTitle: "Planlyze AI",
    heroDescription: "Generate comprehensive business and technical strategies tailored to your specific idea using our advanced AI technology. Special focus on Syrian market data and regional opportunities.",
    tryAiNow: "Try AI Tool",
    heroBadge: "AI-Powered Strategy",
    heroSubtitle1: "From",
    heroSubtitleIdea: "Idea",
    heroSubtitle2: "to",
    heroSubtitlePlan: "Action Plan",
    heroStat1: "AI Analysis",
    heroStat2: "Syrian Focus",
    heroStat3: "Strategy Plans",
    heroStat4: "Tech Startup",
    statsUsers: "Active Users",
    statsReports: "Reports Generated",
    syApps: "Syrian Apps Launched",
    aboutTitle: "What is Planlyze AI?",
    aboutDescription: "Planlyze AI is your intelligent business strategist that transforms your software ideas into actionable plans. Powered by advanced artificial intelligence and enriched with comprehensive Syrian market data, our platform delivers personalized business strategies and technical roadmaps in minutes.",
    featuresTitle: "Comprehensive AI-Powered Solutions",
    feature1Title: "Business Strategy Generation",
    feature1Desc: "Get detailed market analysis, competitor research, and revenue models tailored to your specific industry and target market.",
    feature2Title: "Technical Architecture Planning",
    feature2Desc: "Receive comprehensive technical specifications, technology stack recommendations, and development roadmaps.",
    feature3Title: "Syrian Market Intelligence",
    feature3Desc: "Access specialized insights about Syrian market conditions, local opportunities, and regional business landscapes.",
    feature4Title: "Action Plan Development",
    feature4Desc: "Get step-by-step implementation plans with timelines, milestones, and resource requirements.",
    feature5Title: "Financial Projections",
    feature5Desc: "Get detailed financial forecasts, revenue models, and cost analysis for your business idea.",
    feature6Title: "Competitive Analysis",
    feature6Desc: "Understand your competitive landscape with detailed analysis of market players and positioning strategies.",
    partnersTitle: "Our Partners Through Guidance and Training",
    partnersSubtitle: "Join the ecosystem of innovation and growth",
    benefitsTitle: "Why Choose Planlyze AI?",
    benefit1Title: "Syrian Market Expertise",
    benefit1Desc: "The only AI tool specifically trained on Syrian market data, regulations, and business opportunities.",
    benefit2Title: "Complete Strategy Package",
    benefit2Desc: "Get everything you need: business plan, technical specs, action plan, and pitch deck in one place.",
    benefit3Title: "Instant Results",
    benefit3Desc: "Generate comprehensive strategies in minutes, not weeks of manual research and planning.",
    benefit4Title: "Data-Driven Insights",
    benefit4Desc: "All recommendations backed by real market data, industry trends, and proven methodologies.",
    howItWorksTitle: "How It Works",
    step1Title: "Write Your Idea",
    step1Desc: "Tell us about your software concept and target market",
    step2Title: "AI Analysis",
    step2Desc: "Our AI analyzes your idea against Syrian market data and global trends",
    step3Title: "Get Your Strategy",
    step3Desc: "Receive complete business strategy and technical plan",
    ctaTitle: "Ready to Transform Your Idea?",
    ctaSubtitle: "Join hundreds of Syrian entrepreneurs who've used Planlyze AI to build successful businesses",
    getStarted: "Get Started Now",
    pricingTitle: "Flexible Pricing Plans",
    pricingSubtitle: "Choose the plan that fits your needs",
    freeTier: "Free",
    freeTierBadge: "Forever Free",
    freeTierPrice: "Free",
    freeTierDesc: "Get started with essential insights",
    freeTierFeature1: "Unlimited basic report generation",
    freeTierFeature2: "General market overview & trends",
    freeTierNotIncluded1: "No competitor analysis",
    freeTierNotIncluded2: "No Syrian market data",
    freeTierNotIncluded3: "No AI Assistant access",
    payPerReport: "Entrepreneurial",
    payPerReportPrice: "$10",
    payPerReportDesc: "Complete analysis for serious entrepreneurs",
    payPerReportFeature1: "1 premium report credit",
    payPerReportFeature2: "Detailed competitor analysis",
    payPerReportFeature3: "Syrian market data & local opportunities",
    payPerReportFeature4: "AI-powered strategic recommendations",
    payPerReportFeature5: "Interactive AI Assistant for Q&A",
    payPerReportFeature6: "Export to PDF & Excel formats",
    bundlePackage: "Enterprise",
    bundlePackagePrice: "$90",
    bundlePackageDesc: "Best value - Save 10%",
    bundlePackageFeature1: "10 premium report credits",
    bundlePackageFeature2: "Detailed competitor analysis",
    bundlePackageFeature3: "Syrian market data & local opportunities",
    bundlePackageFeature4: "AI-powered strategic recommendations",
    bundlePackageFeature5: "Interactive AI Assistant for Q&A",
    bundlePackageFeature6: "Export to PDF & Excel formats",
    selectPlan: "Select Plan",
    mostPopular: "Most Popular",
    bestValue: "Best Value",
    faqTitle: "Frequently Asked Questions",
    faq1Q: "What is Planlyze AI?",
    faq1A: "Planlyze AI is an AI-powered platform that generates comprehensive business strategies, technical roadmaps, and pitch decks tailored to your specific software idea, with special focus on Syrian market data.",
    faq2Q: "How long does it take to generate a report?",
    faq2A: "Most reports are generated within 2-5 minutes. The AI analyzes your idea, researches market data, and creates a comprehensive strategy document.",
    faq3Q: "Is my business idea kept confidential?",
    faq3A: "Absolutely. We use end-to-end encryption and never share your ideas with third parties. Your data is protected by strict security measures.",
    faq4Q: "What's included in a premium report?",
          faq4A: "Premium reports include competitor analysis, Syrian market data, AI predictions, risk analysis, interactive AI Assistant for Q&A, and export options in PDF and Excel formats.",
    faq5Q: "Do credits expire?",
    faq5A: "Single credits never expire. Bundle package credits are valid for 12 months from the purchase date.",
    faq6Q: "Can I get a refund?",
          faq6A: "Yes, we offer refunds within 7 days of purchase if you haven't used your credits. Contact our support team for assistance.",
          faq7Q: "What's next after studying my Planlyze report?",
          faq7A: "Your Planlyze report is your strategic foundation. The next steps depend on your goals: you can approach investors with your comprehensive business plan, seek strategic partners to accelerate growth, or proceed directly to market launch with your validated roadmap. We don't provide code—we provide the strategic clarity you need to make informed decisions about your venture's future.",
    contactTitle: "Contact Us",
    contactSubtitle: "Have questions? We're here to help!",
    contactFormName: "Your Name",
    contactFormEmail: "Your Email",
    contactFormMessage: "Your Message",
    contactFormSend: "Send Message",
    footerDesc: "Empowering entrepreneurs to turn software ideas into reality with AI-powered strategies and comprehensive education.",
    legal: "Legal",
    privacyPolicy: "Privacy Policy",
    ideaSecurity: "Idea Security",
    copyright: "© 2024 Planlyze. All rights reserved."
  },
  ar: {
    navAbout: "من نحن",
    navFeatures: "الميزات",
    navPricing: "الأسعار",
    navFAQ: "الأسئلة الشائعة",
    navContact: "تواصل معنا",
    navPartners: "الشركاء",
    navBlog: "المدونة",
    heroTitle: "Planlyze AI",
    heroDescription: "أنشئ استراتيجيات عمل وتقنية شاملة مصممة خصيصاً لفكرتك باستخدام تقنيتنا المتقدمة للذكاء الاصطناعي. تركيز خاص على بيانات السوق السوري والفرص الإقليمية.",
    tryAiNow: "جرب أداة الذكاء الاصطناعي",
    heroBadge: "استراتيجية مدعومة بالذكاء الاصطناعي",
    heroSubtitle1: "من",
    heroSubtitleIdea: "فكرة",
    heroSubtitle2: "إلى",
    heroSubtitlePlan: "خطة عمل",
    heroStat1: "تحليل الذكاء الاصطناعي",
    heroStat2: "التركيز السوري",
    heroStat3: "خطط استراتيجية",
    heroStat4: "للشركات الناشئة",
    statsUsers: "مستخدم نشط",
    statsReports: "تقرير تم إنشاؤه",
    syApps: "التطبيقات السورية المنافسة",
    aboutTitle: "ما هو Planlyze AI؟",
    aboutDescription: "Planlyze AI هو استراتيجي الأعمال الذكي الذي يحول أفكارك البرمجية إلى خطط قابلة للتنفيذ. مدعوم بالذكاء الاصطناعي المتقدم وبيانات السوق السوري الشاملة، تقدم منصتنا استراتيجيات أعمال مخصصة وخرائط طريق تقنية في دقائق.",
    featuresTitle: "حلول شاملة مدعومة بالذكاء الاصطناعي",
    feature1Title: "توليد استراتيجية الأعمال",
    feature1Desc: "احصل على تحليل مفصل للسوق وبحث المنافسين ونماذج الإيرادات المصممة لصناعتك والسوق المستهدف.",
    feature2Title: "تخطيط البنية التقنية",
    feature2Desc: "احصل على مواصفات تقنية شاملة وتوصيات حزمة التقنيات وخرائط طريق التطوير.",
    feature3Title: "ذكاء السوق السوري",
    feature3Desc: "احصل على رؤى متخصصة حول ظروف السوق السوري والفرص المحلية والمشاهد التجارية الإقليمية.",
    feature4Title: "تطوير خطة العمل",
    feature4Desc: "احصل على خطط تنفيذ خطوة بخطوة مع الجداول الزمنية والمراحل ومتطلبات الموارد.",
    feature5Title: "التوقعات المالية",
    feature5Desc: "احصل على توقعات مالية مفصلة ونماذج إيرادات وتحليل تكاليف لفكرتك التجارية.",
    feature6Title: "التحليل التنافسي",
    feature6Desc: "افهم المشهد التنافسي مع التحليل المفصل للاعبين في السوق واستراتيجيات التموضع.",
    partnersTitle: "شركاؤنا بالإرشاد والتدريب",
    partnersSubtitle: "انضم إلى نظام الابتكار والنمو",
    benefitsTitle: "لماذا تختار Planlyze AI؟",
    benefit1Title: "خبرة السوق السوري",
    benefit1Desc: "<span class='font-bold text-orange-500'>الأداة الوحيدة</span> للذكاء الاصطناعي المدربة خصيصاً على بيانات السوق السوري واللوائح والفرص التجارية.",
    benefit2Title: "حزمة استراتيجية كاملة",
    benefit2Desc: "احصل على كل ما تحتاجه: خطة عمل ومواصفات تقنية وخطة عمل وعرض تقديمي في مكان واحد.",
    benefit3Title: "نتائج فورية",
    benefit3Desc: "أنشئ استراتيجيات شاملة في دقائق، وليس أسابيع من البحث والتخطيط اليدوي.",
    benefit4Title: "رؤى مدفوعة بالبيانات",
    benefit4Desc: "جميع التوصيات مدعومة ببيانات السوق الحقيقية واتجاهات الصناعة والمنهجيات المجربة.",
    howItWorksTitle: "كيف يعمل",
    step1Title: "اكتب فكرتك",
    step1Desc: "أخبرنا عن مفهوم برنامجك والسوق المستهدف",
    step2Title: "تحليل الذكاء الاصطناعي",
    step2Desc: "يحلل ذكاؤنا الاصطناعي فكرتك مقابل بيانات السوق السوري والاتجاهات العالمية",
    step3Title: "احصل على استراتيجيتك",
    step3Desc: "احصل على استراتيجية عمل كاملة وخطة تقنية",
    ctaTitle: "هل أنت مستعد لتحويل فكرتك؟",
    ctaSubtitle: "انضم إلى مئات رواد الأعمال السوريين الذين استخدموا Planlyze AI لبناء أعمال ناجحة",
    getStarted: "ابدأ الآن",
    pricingTitle: "خطط أسعار مرنة",
    pricingSubtitle: "اختر الخطة التي تناسب احتياجاتك",
    freeTier: "مجاني",
    freeTierBadge: "مجاني للأبد",
    freeTierPrice: "مجاناً",
    freeTierDesc: "ابدأ برؤى أساسية",
    freeTierFeature1: "توليد تقارير أساسية غير محدود",
    freeTierFeature2: "نظرة عامة على السوق والاتجاهات",
    freeTierNotIncluded1: "بدون تحليل المنافسين",
    freeTierNotIncluded2: "بدون بيانات السوق السوري",
    freeTierNotIncluded3: "بدون مساعد الذكاء الاصطناعي",
    payPerReport: "ريادي",
    payPerReportPrice: "$10",
    payPerReportDesc: "تحليل شامل لرواد الأعمال الجادين",
    payPerReportFeature1: "رصيد تقرير مميز واحد",
    payPerReportFeature2: "تحليل تفصيلي للمنافسين",
    payPerReportFeature3: "بيانات السوق السوري والفرص المحلية",
    payPerReportFeature4: "توصيات استراتيجية مدعومة بالذكاء الاصطناعي",
    payPerReportFeature5: "مساعد ذكاء اصطناعي تفاعلي للأسئلة",
    payPerReportFeature6: "تصدير بصيغ PDF و Excel",
    bundlePackage: "المؤسسات",
    bundlePackagePrice: "$90",
    bundlePackageDesc: "أفضل قيمة - وفّر 10٪",
    bundlePackageFeature1: "10 أرصدة تقارير مميزة",
    bundlePackageFeature2: "تحليل تفصيلي للمنافسين",
    bundlePackageFeature3: "بيانات السوق السوري والفرص المحلية",
    bundlePackageFeature4: "توصيات استراتيجية مدعومة بالذكاء الاصطناعي",
    bundlePackageFeature5: "مساعد ذكاء اصطناعي تفاعلي للأسئلة",
    bundlePackageFeature6: "تصدير بصيغ PDF و Excel",
    selectPlan: "اختر الخطة",
    mostPopular: "الأكثر شعبية",
    bestValue: "الأفضل قيمة",
    faqTitle: "الأسئلة الشائعة",
    faq1Q: "ما هو Planlyze AI؟",
    faq1A: "Planlyze AI هي منصة مدعومة بالذكاء الاصطناعي تولد استراتيجيات أعمال شاملة وخرائط طريق تقنية وعروض تقديمية مصممة لفكرتك البرمجية، مع تركيز خاص على بيانات السوق السوري.",
    faq2Q: "كم من الوقت يستغرق إنشاء تقرير؟",
    faq2A: "معظم التقارير تُنشأ خلال 2-5 دقائق. يحلل الذكاء الاصطناعي فكرتك ويبحث في بيانات السوق وينشئ وثيقة استراتيجية شاملة.",
    faq3Q: "هل تبقى فكرتي التجارية سرية؟",
    faq3A: "بالتأكيد. نستخدم التشفير من طرف إلى طرف ولا نشارك أفكارك مع أطراف ثالثة أبداً. بياناتك محمية بتدابير أمنية صارمة.",
    faq4Q: "ما الذي يتضمنه التقرير المميز؟",
    faq4A: "التقارير المميزة تتضمن تحليل المنافسين، بيانات السوق السوري، تنبؤات الذكاء الاصطناعي، تحليل المخاطر، مساعد ذكاء اصطناعي تفاعلي للأسئلة، وخيارات التصدير بصيغ PDF و Excel.",
    faq5Q: "هل تنتهي صلاحية الأرصدة؟",
    faq5A: "الأرصدة الفردية لا تنتهي صلاحيتها أبداً. أرصدة حزم الباقات صالحة لمدة 12 شهراً من تاريخ الشراء.",
    faq6Q: "هل يمكنني استرداد المبلغ؟",
    faq6A: "نعم، نقدم استرداد المبلغ خلال 7 أيام من الشراء إذا لم تستخدم أرصدتك. تواصل مع فريق الدعم للمساعدة.",
    faq7Q: "ما الخطوة التالية بعد دراسة تقرير Planlyze؟",
    faq7A: "تقرير Planlyze هو أساسك الاستراتيجي. الخطوات التالية تعتمد على أهدافك: يمكنك التواصل مع المستثمرين بخطة عملك الشاملة، أو البحث عن شركاء استراتيجيين لتسريع النمو، أو الانطلاق مباشرة إلى السوق بخارطة طريقك المُحققة. نحن لا نقدم كود برمجي—نقدم لك الوضوح الاستراتيجي الذي تحتاجه لاتخاذ قرارات مدروسة حول مستقبل مشروعك.",
    contactTitle: "تواصل معنا",
    contactSubtitle: "لديك أسئلة؟ نحن هنا للمساعدة!",
    contactFormName: "اسمك",
    contactFormEmail: "بريدك الإلكتروني",
    contactFormMessage: "رسالتك",
    contactFormSend: "إرسال الرسالة",
    footerDesc: "تمكين رواد الأعمال من تحويل الأفكار البرمجية إلى واقع من خلال استراتيجيات مدعومة بالذكاء الاصطناعي وتعليم شامل.",
    legal: "قانوني",
    privacyPolicy: "سياسة الخصوصية",
    ideaSecurity: "أمن الأفكار",
    copyright: "© 2024 Planlyze. جميع الحقوق محفوظة."
  }
};
