"""Add description and min_purchase fields to discount_codes

Revision ID: 0445674735fc
Revises: 5eb002604463
Create Date: 2025-12-19 13:10:42.845152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0445674735fc'
down_revision = '5eb002604463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_ar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('min_purchase_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.drop_column('min_purchase_amount')
        batch_op.drop_column('description_ar')
        batch_op.drop_column('description_en')

    # ### end Alembic commands ###
