"""Add report_language column to analyses

Revision ID: 23fa9123f535
Revises: ea52bc78bf39
Create Date: 2025-12-20 21:56:10.620818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fa9123f535'
down_revision = 'ea52bc78bf39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_language', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('report_language')

    # ### end Alembic commands ###
