"""remove onboarding

Revision ID: 53ef3ba51768
Revises: 805c783b8003
Create Date: 2025-12-13 18:03:36.728433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ef3ba51768'
down_revision = '805c783b8003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('onboarding_step')
        batch_op.drop_column('onboarding_completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('onboarding_step', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
