"""Initial migration with onboarding fields

Revision ID: 805c783b8003
Revises: 
Create Date: 2025-12-13 17:11:06.088794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805c783b8003'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_step', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('onboarding_step')
        batch_op.drop_column('onboarding_completed')

    # ### end Alembic commands ###
