"""Add discount fields to payments

Revision ID: 9a2002b0c7de
Revises: 23fa9123f535
Create Date: 2025-12-23 18:39:26.752063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2002b0c7de'
down_revision = '23fa9123f535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount_code')
        batch_op.drop_column('original_amount')

    # ### end Alembic commands ###
