"""Add report_type pending_transaction_id last_error to analyses

Revision ID: ea52bc78bf39
Revises: 6e8ca3fc7245
Create Date: 2025-12-20 14:59:59.095404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea52bc78bf39'
down_revision = '6e8ca3fc7245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pending_transaction_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'transactions', ['pending_transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_error')
        batch_op.drop_column('pending_transaction_id')
        batch_op.drop_column('report_type')

    # ### end Alembic commands ###
